name: Weekly Release

on:
  schedule:
    - cron: '0 17 * * 5'
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  release:
    name: Create Weekly Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure full history is fetched

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Grant execute permissions for build script
        run: chmod +x ./bin/build-plugin-zip.sh

      - name: Generate plugin zip file
        run: ./bin/build-plugin-zip.sh -b

      - name: Upload build file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: plugin-zip
          path: ./continuous-integrations.zip
