name: PHPCS on PR

on:
  pull_request:
    branches:
      - develop
      - master
      - 'release/**'
      - 'rc/**'

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'  # or any version you are using
          tools: composer

      - name: Install dependencies
        run: |
          composer install

      - name: Determine changed files
        id: filter
        uses: dorny/paths-filter@v2
        with:
          list-files: shell
          filters: |
            php:
              - 'includes/**/*.php'
              - 'includes/**'

      - name: Run PHPCS
        if: steps.filter.outputs.php_files != ''
        run: |
          ./vendor/bin/phpcs --standard=phpcs.xml ${GITHUB_WORKSPACE}/${{ steps.filter.outputs.php_files }}
