name: PHPCS on PR

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'  # or any version you are using
          tools: composer

      - name: Install dependencies
        run: |
          composer install

      - name: Determine changed files
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            php:
              - 'includes/**/*.php'

      - name: Debug Filter Output
        run: |
          echo "Filter php = ${{ steps.filter.outputs.php }}"
          echo "Matching files: ${{ steps.filter.outputs.files }}"

      - name: Run PHPCS
        if: steps.filter.outputs.php == 'true'
        run: |
          ./vendor/bin/phpcs --standard=phpcs.xml ${GITHUB_WORKSPACE}/${{ steps.filter.outputs.files }}
