name: End-to-End Tests

on:
  pull_request:
    branches:
      - develop

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  e2e-playwright:
    name: Playwright - ${{ matrix.part }}
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}

      - name: Setup Node.js and install dependencies
        uses: ./.github/setup-node

      - name: NPM build
        run: npm run build

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      # Since Composer dependencies are installed using `composer update` and no lock file is in version control,
      # passing a custom cache suffix ensures that the cache is flushed at least once per week.
      - name: Install Composer dependencies
        uses: ramsey/composer-install@57532f8be5bda426838819c5ee9afb8af389d51a # v3.0.0
        with:
          custom-cache-suffix: $(/bin/date -u --date='last Mon' "+%F")
          composer-options: '--no-dev'

      - name: Install Playwright dependencies
        run: |
          npx playwright install chromium firefox webkit --with-deps

      - name: Install WordPress and start the server
        run: |
          npm run env:start

      - name: Run the tests
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test:e2e -- --shard=${{ matrix.part }}/${{ matrix.totalParts }}

      - name: Archive debug artifacts (screenshots, traces)
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        if: ${{ !cancelled() }}
        with:
          name: failures-artifacts--${{ matrix.part }}
          path: artifacts/test-results
          if-no-files-found: ignore

      - name: Archive flaky tests report
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        if: ${{ !cancelled() }}
        with:
          name: flaky-tests-report--${{ matrix.part }}
          path: flaky-tests
          if-no-files-found: ignore
